### ISSUE TITLE
Script Tasks: file configured does not exist

### ISSUE THREAD

**Issue by neoray12** [SAP-samples/s4hana-ext-approve-payment-data#1]
Hello,
After deploying the workflow, it show up 4 errors from 4 script task.

![image](https://user-images.githubusercontent.com/35328954/67629303-a0f63a00-f8ae-11e9-8f9a-5022f3329026.png)

I think the file do exist and I have no idea why this error keep occur.
Kindly advise.

**Comment by meakgoz2** [comment]
Hi Neo,

Thanks for reaching us out. 
Workflow applications have their own project structure. The deployer searches all the files with respect to root foler. So, you need to import all the workflow applications separately as described in the [tutorial](https://help.sap.com/viewer/b0e8d558ba2f47f5b02a3fc0ac9edc34/SHIP/en-US/3f45bbda8bcd450d8e91cfffaf50fd76.html). Only then workflow project will have its predefined folder structure.
